# 🔐 Vault Keeper: Fly.io deployment configuration for XO Agent webhook system
# Preserving digital essence with production-ready deployment

app = "xo-agent"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  # 🔐 Vault Keeper: Required secrets for digital essence protection
  XO_AGENT_SECRET = ""
  XO_ENV = "production"
  XO_DEPLOYMENT = "fly.io"
  
  # Optional: DNS and deployment configuration
  CLOUDFLARE_API_TOKEN = ""
  CLOUDFLARE_ZONE_ID = ""
  
  # Service URLs for cosmic alignment
  XO_VAULT_URL = "https://vault.21xo.com"
  XO_INBOX_URL = "https://inbox.21xo.com"
  XO_PREVIEW_URL = "https://preview.21xo.com"
  XO_AGENT0_URL = "https://agent.21xo.com"
  
  # Logging and monitoring
  LOG_LEVEL = "INFO"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/agent/health"

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/agent/test"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[metrics]
  port = 9091
  path = "/metrics"

# 🔐 Vault Keeper: Health check configuration
[checks]
[checks.health]
  type = "http"
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/agent/health"
  protocol = "tls"
  tls_skip_verify = false

[checks.webhook]
  type = "http"
  interval = "60s"
  timeout = "10s"
  grace_period = "30s"
  method = "POST"
  path = "/agent/test"
  protocol = "tls"
  tls_skip_verify = false
  headers = { "Content-Type" = "application/json" }
  body = '{"data": {"test": "vault_keeper_health_check"}}'

# 🔐 Vault Keeper: Scaling configuration for digital essence preservation
[scaling]
  min = 1
  max = 3
  target_cpu_percent = 70