[project]
name = "agent0"
version = "0.1.0"
description = "Agent0 module"
authors = [{ name = "XO", email = "co@21xo.com" }]
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
