# Shared data and test pulse generators for use across pulse modules

from datetime import datetime
from pathlib import Path

def generate_test_pulse_data(slug="test_pulse"):
    """Generate a minimal test pulse dictionary for reuse across modules."""
    return {
        "title": "Test Pulse",
        "slug": slug,
        "timestamp": datetime.utcnow().isoformat(),
        "tags": ["test", "pulse"],
        "content": "This is a test pulse content.",
    }

def generate_test_pulse(c=None, slug="test_pulse"):
    """
    Generate a test pulse file and directory structure.
    
    Args:
        c: Fabric context (optional)
        slug: Pulse slug name (default: "test_pulse")
    """
    if c is None:
        # Return just the data if no context provided
        return generate_test_pulse_data(slug)

def generate_test_pulse(c, slug="test_pulse"):
    """
    Generate a test pulse file and directory structure.
    
    Args:
        c: Fabric context
        slug: Pulse slug name (default: "test_pulse")
    """
    # Create the pulse directory
    pulse_dir = Path(f"content/pulses/{slug}")
    pulse_dir.mkdir(parents=True, exist_ok=True)
    
    # Create the main pulse file
    pulse_file = pulse_dir / f"{slug}.mdx"
    pulse_content = f"""---
title: "Test Pulse - {slug}"
slug: "{slug}"
timestamp: "{datetime.utcnow().isoformat()}"
tags: ["test", "pulse", "generated"]
---

# Test Pulse: {slug}

This is a test pulse generated for development and testing purposes.

## Content

- **Slug**: {slug}
- **Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
- **Purpose**: Testing pulse sync and workflow

## Test Data

This pulse contains sample content for testing the pulse workflow including:
- Frontmatter metadata
- Markdown content
- Tags and timestamps

---
*Generated by pulse sync workflow*
"""
    
    pulse_file.write_text(pulse_content)
    print(f"🧪 Generated test pulse file: {pulse_file}")
    
    # Create an index.mdx file as well
    index_file = pulse_dir / "index.mdx"
    index_content = f"""---
title: "Test Pulse Index - {slug}"
slug: "{slug}"
type: "pulse"
---

# Test Pulse Index

This is the index file for the test pulse: **{slug}**

## Quick Links

- [Main Pulse]({slug}.mdx)
- [Generated]: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}

---
*Auto-generated index*
"""
    
    index_file.write_text(index_content)
    print(f"📄 Generated index file: {index_file}")
    
    return {
        "slug": slug,
        "title": f"Test Pulse - {slug}",
        "path": pulse_file,
        "index_path": index_file,
        "timestamp": datetime.utcnow().isoformat()
    }

test_pulse_data = {
    "slug": "sample-pulse",
    "title": "Sample Pulse",
    "summary": "This is a sample test pulse.",
    "content": "# Sample Pulse\n\nThis is a markdown content example.",
    "tags": ["sample", "test"],
    "timestamp": datetime.utcnow().isoformat(),
    "path": Path("content/pulses/sample-pulse/index.mdx")
}