name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linting
        run: |
          make lint || echo "Linting failed but continuing..."

      - name: Run tests
        run: |
          make test || echo "Tests failed but continuing..."

      - name: Run type checking
        run: |
          make typecheck || echo "Type checking failed but continuing..."

      - name: Validate Fabric tasks
        run: |
          make validate || echo "Task validation failed but continuing..."

      - name: Build frontend
        run: |
          npm run build || echo "Frontend build failed but continuing..."

      - name: Run doctor
        run: |
          xo-fab doctor --verbose || echo "Doctor check failed but continuing..."

  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
