name: Sync Docs to xo-core-docs

on:
  push:
    branches: [main]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Generate Docs
        run: |
          pip install mkdocs
          mkdocs build

      - name: Push to xo-core-docs
        uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.XO_DOCS_APP_ID }}
          private_key: ${{ secrets.XO_DOCS_PRIVATE_KEY }}

      - name: Push to target repo
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global user.email "bot@xo-vault.com"
          git config --global user.name "xo-docs-bot"
          git clone https://x-access-token:${GH_TOKEN}@github.com/xo-ecosystem/xo-core-docs.git
          cp -r site/* xo-core-docs/
          cd xo-core-docs
          git add .
          git commit -m "🔄 Auto-update from xo-core"
          git push
