name: Webhook Deploy

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
      run: |
        cd contracts
        npm ci
        npx hardhat run scripts/00_deploy.ts --network baseSepolia

    - name: Deploy to staging
      if: github.ref == 'refs/heads/staging'
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
      run: |
        cd contracts
        npm ci
        npx hardhat run scripts/00_deploy.ts --network baseSepolia
